# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nibs_store' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nibs_store
	pod 'Firebase/Core'
	pod 'Firebase/Database'

  target 'nibs_storeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nibs_storeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
