# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nibs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nibs
  pod ‘Alamofire’
  pod ‘Firebase/Core'

  pod ‘Firebase/Database’
  pod ‘Firebase/Storage’

  target 'nibsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nibsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
